name: vit_ap_student_app
description: "VITAP Student"
publish_to: "none"
version: 2.2.1+20

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  share_plus: ^11.0.0
  intl: ^0.20.0
  device_info_plus: ^11.2.0
  timeline_tile: ^2.0.0
  lottie: ^3.3.1
  animations: ^2.0.11
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.2.1
  firebase_core: ^3.13.1
  json_annotation: ^4.9.0
  wiredash: 2.5.0
  timeago: ^3.7.0
  wave: ^0.2.2
  permission_handler: ^12.0.0+1
  timezone: ^0.10.1
  package_info_plus: ^8.0.2
  app_settings: ^6.1.1
  home_widget: ^0.7.0+1
  internet_connection_checker_plus: ^2.7.2
  fpdart: ^1.1.1
  riverpod_annotation: ^2.6.1
  path_provider: ^2.1.5
  objectbox: ^4.2.0
  objectbox_flutter_libs: ^4.2.0
  get_it: ^8.0.3
  iconsax_flutter: ^1.0.0
  flutter_native_splash: ^2.4.6
  firebase_analytics: ^11.4.6
  html: ^0.15.6
  upgrader: ^12.3.0
  syncfusion_flutter_pdfviewer: ^28.1.33
  open_file: ^3.5.10
  webview_flutter: ^4.13.0
  lib_vtop:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5
  flutter_lints: ^5.0.0
  objectbox_generator: ^4.2.0
  freezed: ^3.1.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/pfp/
    - assets/images/logo/
    - assets/images/icons/
    - assets/weather_icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
